server:
    port: 8080
application:
    message: and this is a SpringBoot App
    appname: with Axon3!
logging.file: app.log
management.port: 8082
management.addres: 127.0.0.1
management.context-path: /admin 
endpoints.health.enabled: true
security.basic.enabled: false
management.security.enabled: false

#spring.data.mongodb.uri: mongodb://host:port/db
#spring.data.mongodb.uri: mongodb://0.0.0.0:27017/thedarkcoderrises
#spring.data.mongodb.uri: mongodb://mongo:27017/test

#kafka.url: localhost:9092

logging:
    level:
        root: ERROR
        org.springframework.web: ERROR
        com.circuitbreaker: DEBUG
        org.hibernate: ERROR
    file: logs/Ecart.log
    pattern:
        console:
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring: 
    profiles: development
server:
    port: 9090
application: 
    message: I am in DEV ENV
---
spring:
    profiles: production
server:
    port: 10010
application:
    message: I am in PROD ENV
